language: node_js
env:
  global:
    - GH_REF: github.com/w3c/css-aam.git
    - secure: "mP3LRpCSdV78BXka0Gfiy4dagEarDcQH9Apmle0Sq4sEOF1goIJwmIyb3yRfO2986YR+guLSKMBc8qrvYM4wUaFjF3woYT6wSSnFjN7B1AbMqbiIt1ij4fMZ/PJoDHO61FCv3AY/WfvJfAhsFN4iXk8Nuy93EgSZBP22CE6UDcpFb+MfEsabW70kCjfDJWABwCdVrQFkDC9yDpmiaARocDb3I6vU1wPTYpgDyeeYsQSei9AvVyy5QS9gkrjTMPeol+kpt0HcQRruQcfnumG0OO/nR+pIBWEgPk1DkSLxdXdb0RJs1Vc402+Rpr5tEYkD3Eyjqt2nyp+xIL+oUPIikhWncsQYq0mvJoslx/WqCKBs1Sr0SMX4XmAPxL6UlLIskoKfY+t0WwqngOLu1ew4hOmXzBz95X5P9IjGxk+pcQ5XwTwW5SXJg012Bvj8Exp49ElOlwAg5B4lbcvwFOZIz1oGJPV4OqEjeGNaSV+lR3Qzmg25ZUai5f/Q/cAtVjPsyvIdxc3lEhiB7wsCysgdpwziY+uY3Gv095nQDMYcyZxtj47+EMNQuEiAQ/Ey2rRpqpP6HyBavTIv8sSJ7j3XYILT9UKMtLVzowTxu1WNt+F7jIu6r8qpVD50fwHf599kLr+EELBRP3NiT78EQ153TqnFshT7DQKx8Url+2rVJuo="
    
git:
  depth: 3
  
branches:
  only:
    master

before_script:
  - git config --global user.email "cooper@w3.org"
  - git config --global user.name "michael-n-cooper"
  
script:
  - cd ../..
  - mkdir gh-pages
  - cd gh-pages
  - git clone --depth=1 --branch=gh-pages https://github.com/w3c/css-aam.git
  - cd css-aam
  - curl https://labs.w3.org/spec-generator/?type=respec"&"url=https://rawgit.com/w3c/css-aam/master/index.html -o index.html -f

after_success:
  - git add -A .
  - git commit -m "Generated by TRAVIS-CI"
  - git push "https://${GH_TOKEN}@${GH_REF}" gh-pages
